### ISSUE TITLE
Strict mode for undefined variables

### ISSUE THREAD

**Issue by oTree-org** [dmulholl/ibis#2]
I've been using Ibis (markup as well as API for custom tags) and so far it's perfect!

I'm happy to contribute an implementation of a global strict mode for undefined variables, if you feel that fits well with this project.

Report errors such as:

- undefined variables: `{{ bogus }}`
- undefined attributes: `{{ real.bogus }}`
- undefined variables used in tags, especially `{% if %}` & `{% for %}`

(In some situations it's useful to have undefined variables, but then I can check `|undefined`, great.)

Here are the steps I see:
- ibis.errors: add a subclass called `StrictUndefined` that raises an error on all methods like `__str__`, `__bool__`, etc.
- In `IfNode.eval_condition()`, fix the catch-all `except` (I see you already have a note about this)
- In `Context.resolve()`, change:

            except (TypeError, AttributeError):
                obj = Undefined()

To:

            except (TypeError, AttributeError):
                obj = StrictUndefined() if USE_STRICT else Undefined()

Jinja allows passing StrictUndefined as an arg to the Environment and Template constructor, but personally I would be satisfied with a toggle through global var like `ibis.USE_STRICT = True` or env var.

I can do all the above by patching Ibis at runtime, but may be better to contribute upstream, so that it integrates well.

Another consideration is whether, as discussed previously, the line numbers of undefined variables would be reported.
(This also seems necessary for CallError, which is raised during method call exceptions.)

**Comment by dmulholl** [comment]
This is an interesting idea. I'm going to have a think about this and get back to you!

**Comment by dmulholl** [comment]
Okay, some thoughts. I definitely want to clean up the handling of the `Undefined` type in v2 as it was a weak point in v1. I've introduced a pair of filters to help with this in `2.0.0-alpha.2`:

1.  A boolean filter `is_defined` for testing if a variable has been resolved or not:

        {% if foo.bar|is_defined %}
            do stuff with {{ foo.bar }}
        {% endif %}

2. A fallback filter `if_undefined` for supplying a default value for undefined variables:

        {{ foo.bar|if_undefined("baz") }}

    (This is just the old `undefined` filter given a clearer name.)

I think between them these two filters cover a lot of the pain points.

I'm not keen on the idea of introducing multiple `Undefined` types. It's not that it would be difficult to implement them, it's that it would be difficult to explain their use clearly and simply in the documentation. (I get why Jinja uses them but Jinja has to cover every use case and its documentation reflects that!)

I'm definitely open to the idea of an opt-in strict handling mode for undefined variables where instead of returning an `Undefined` instance, `Context.resolve()` raises a `TemplateRenderingError` if it can't resolve a variable name.

The filters above wouldn't work in this mode as the exception would already have been raised but I can add a boolean `is_defined("foo.bar")` function which wouldn't be affected.

Let me know if you have any thoughts on any of this!

**Comment by oTree-org** [comment]
Hi, that sounds good to me! For example:

```
{% if is_defined("user") and user.is_logged_in %}
    logout 
{% endif %}
```

**Comment by oTree-org** [comment]
It seems similar to the Python way:

```
if hasattr(obj, "render"):
    obj.render()
```

So the design seems fine to me, and satisfies my use cases.

**Comment by dmulholl** [comment]
Excellent. I like this idea. I can implement the flag as a keyword argument to the `Template.render()` method:

    output = template.render(data, strict_mode=True)

Makes it easy to opt into and easy to explain. 

It's probably worth raising a specific `UndefinedVariable` exception in these cases to make them easy to isolate. 

I should have an implementation ready in the next day or two. Further suggestions welcome!

**Comment by oTree-org** [comment]
OK sounds great! I sketched out some code:

Context.resolve:

```
    def resolve(self, varstring):
        result = self
        parts = []
        for token in varstring.split('.'):
            parts.append(token)
            try:
                result = result[token]
            except:
                try:
                    result = getattr(result, token)
                except:
                    if strict_mode:
                        raise UndefinedVariableError('.'.join(parts))
                    return Undefined()
        return result
```

Expression:

    def _resolve_variable(self, context):
        template_id = self.token.template_id
        line_number = self.token.line_number

        try:
            obj = context.resolve(self.varstr)
        except UndefinedVariableError as exc:
            msg = f"Undefined variable '{exc.args[0]}'"
            raise TemplateRenderingError(msg, template_id, line_number)

        if callable(obj):
            try:
                obj = obj(*self.varargs)
            except Exception as exc:
                msg = f"Error calling function '{self.varstr}' "
                raise TemplateRenderingError(msg, template_id, line_number) from exc

        return self._apply_filters_to_variable(obj)

**Comment by dmulholl** [comment]
Thanks, I like the idea of reassembling the variable string for the error message to show where it failed.

I've just pushed `2.0.0-alpha.4` with strict mode support.

**Comment by oTree-org** [comment]
Nice, I will try it out!
