### ISSUE TITLE
Use "raise from" with caught exceptions

### ISSUE THREAD

**Issue by oTree-org** [dmulholl/ibis#3]
I think it would help to use exception chaining ("raise from") when raising TemplateError, so the original exception is accessible:

For example:

            except Exception as exc:
                msg = f"Error calling function '{self.varstr}' "
                msg += f"in template '{self.token.template_id}', line {self.token.line_number}."
                raise TemplateRenderingError(msg, self.token.template_id, self.token.line_number) from exc

Here is an example of using the chained exception:

    try:
        return HTMLResponse(ibis_loader(template_name).render(context))
    except TemplateRenderingError as exc:
        if exc.__cause__:
            original_exc = exc.__cause__
            raise type(original_exc)(
                f'{original_exc} ({exc.template_id}, line {exc.line_number})'
            )
        raise

To produce:

`TypeError: url_for() takes 2 positional arguments but 3 were given (app/Base.html, line 51)`

What do you think?

**Comment by dmulholl** [comment]
I've actually been operating under the assumption that this happens automatically already - that if you raise a new exception from within an `except` handler the original exception is automatically chained unless you specifically use `raise ... from None`.

I think it might be called 'implicit exception chaining', something like that. I'll have to look into this again, it's been a while since I looked it up, but if it isn't happening automatically I'll certainly add `raise from X` wherever appropriate. I've already been adding `raise from None` in all the cases where it didn't make sense.

If you find any good documentation, send me a link :)

**Comment by dmulholl** [comment]
Apparently implicit chaining sets `__context__` rather than `__cause__`. Decent explanations here https://stackoverflow.com/a/11235957 and here https://stackoverflow.com/a/33822606.

I'll add explicit chaining in the next release, didn't realise I was being short chained. 

Thanks, learned something useful from that!
