### ISSUE TITLE
Objects with __call__ method have problem in templates

### ISSUE THREAD

**Issue by oTree-org** [dmulholl/ibis#6]
I am using wtforms and tried laying out radio buttons as described here: https://wtforms.readthedocs.io/en/2.3.x/fields/#wtforms.fields.RadioField

Below is my code:

```
import wtforms
from ibis import Template


class MyForm(wtforms.Form):

    radio = wtforms.RadioField(
        choices=['a', 'b'],
    )

res = Template("""
{% for subfield in form.radio %}
    <tr>
        <td>{{ subfield }}</td>
        <td>{{ subfield.label }}</td>
    </tr>
{% endfor %}
""").render(form=MyForm())


print(res)
```

The output is about 1000 lines of HTML that look like this:

```
    <tr>
        <td><</td>
        <td></td>
    </tr>

    <tr>
        <td>u</td>
        <td></td>
    </tr>

    <tr>
        <td>l</td>
        <td></td>
    </tr>

    <tr>
        <td> </td>
        <td></td>
    </tr>

...
```

The reason is that fields in wtforms define `__call__` as well as `__iter__`. `__call__` renders the field as HTML, and `__iter__` allows iteration over the field's members (e.g. individual radio buttons in a radio select widget). Since the object is callable, Ibis evaluates it first, turning it to a string. So when ForNode loops over it, it is actually iterating a string, character by character. (So, as you can see above, it is iterating over the first characters of a `<ul>` tag.)

This problem does not occur in Django templates because Django checks for an attribute `do_not_call_in_templates` before calling a function. WTForms fields set this attribute.

That is one solution. Another would be to tighten the conditions for calling a variable. For example, only call variables if they are functions or methods, but not regular objects with a `__call__` method.

Another solution would be to not automatically call variables, but rather require an explicit `()`.

**Comment by dmulholl** [comment]
That's hilariously unexpected behaviour.

Automatically calling variables that resolve to callables was something I copied from Django which needs it because it uses colon-syntax for arguments and can't distinguish between a reference and a call without arguments. 

Colon-syntax for arguments was also something I copied from Django originally - I added bracket-syntax and supported both simultaneously. I decided at some point that it was a bad idea (for just this reason!) and 'undocumented' it in preparation for ripping it out at some point. I'd actually forgotten about it though.

I've done that now in `2.0.0-rc2`. Colon-syntax is no longer supported and callables are no longer called automatically, you have to explicitly call them using `()`.

**Comment by oTree-org** [comment]
OK sounds reasonable to me! Thanks!
